"""standardize integration models to english

Revision ID: 2b1a8f9c3d4e
Revises: 14929e5630b6
Create Date: 2024-07-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1a8f9c3d4e'
down_revision = '14929e5630b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('integrations', 'nome', new_column_name='name', existing_type=sa.String(100), nullable=False)
    op.alter_column('integrations', 'tipoConnessione', new_column_name='connection_type', existing_type=sa.String(50))
    op.alter_column('integrations', 'configurazione', new_column_name='configuration', existing_type=sa.JSON())
    op.alter_column('integrations', 'ultimaSincronizzazione', new_column_name='last_sync', existing_type=sa.DateTime())
    op.alter_column('integrations', 'prossimaSincronizzazione', new_column_name='next_sync', existing_type=sa.DateTime())
    op.alter_column('integrations', 'messaggiInCoda', new_column_name='messages_in_queue', existing_type=sa.Integer())
    op.alter_column('integrations', 'messaggiProcessati', new_column_name='messages_processed', existing_type=sa.Integer())
    op.alter_column('integrations', 'ultimoErrore', new_column_name='last_error', existing_type=sa.Text())
    op.alter_column('integrations', 'abilitato', new_column_name='is_enabled', existing_type=sa.Boolean())
    op.alter_column('integrations', 'scheduleConfig', new_column_name='schedule_config', existing_type=sa.JSON())

    op.alter_column('integration_logs', 'azione', new_column_name='action', existing_type=sa.String(100))
    op.alter_column('integration_logs', 'messaggio', new_column_name='message', existing_type=sa.Text())
    op.alter_column('integration_logs', 'dettagli', new_column_name='details', existing_type=sa.JSON())
    op.alter_column('integration_logs', 'durata_ms', new_column_name='duration_ms', existing_type=sa.Integer())
    op.alter_column('integration_logs', 'record_processati', new_column_name='records_processed', existing_type=sa.Integer())
    op.alter_column('integration_logs', 'record_errori', new_column_name='records_with_errors', existing_type=sa.Integer())
    op.alter_column('integration_logs', 'successo', new_column_name='is_successful', existing_type=sa.Boolean())
    op.alter_column('integration_logs', 'errore', new_column_name='error_message', existing_type=sa.Text())

    op.alter_column('integration_credentials', 'nome', new_column_name='name', existing_type=sa.String(100), nullable=False)
    op.alter_column('integration_credentials', 'valore_criptato', new_column_name='encrypted_value', existing_type=sa.Text(), nullable=False)
    op.alter_column('integration_credentials', 'valido_dal', new_column_name='valid_from', existing_type=sa.DateTime())
    op.alter_column('integration_credentials', 'valido_fino', new_column_name='valid_until', existing_type=sa.DateTime())
    op.alter_column('integration_credentials', 'model_metadata', new_column_name='credential_metadata', existing_type=sa.JSON())

    op.alter_column('integration_mappings', 'entita', new_column_name='entity', existing_type=sa.String(50))
    op.alter_column('integration_mappings', 'campi_origine', new_column_name='source_fields', existing_type=sa.JSON(), nullable=False)
    op.alter_column('integration_mappings', 'campi_destinazione', new_column_name='destination_fields', existing_type=sa.JSON(), nullable=False)
    op.alter_column('integration_mappings', 'trasformazioni', new_column_name='transformations', existing_type=sa.JSON())
    op.alter_column('integration_mappings', 'validazioni', new_column_name='validations', existing_type=sa.JSON())
    op.alter_column('integration_mappings', 'attivo', new_column_name='is_active', existing_type=sa.Boolean())

    op.alter_column('edi_messages', 'tipo_messaggio', new_column_name='message_type', existing_type=sa.String(50))
    op.alter_column('edi_messages', 'numero_messaggio', new_column_name='message_number', existing_type=sa.String(100))
    op.alter_column('edi_messages', 'direzione', new_column_name='direction', existing_type=sa.String(10))
    op.alter_column('edi_messages', 'formato', new_column_name='format', existing_type=sa.String(20))
    op.alter_column('edi_messages', 'data_invio', new_column_name='sent_at', existing_type=sa.DateTime())
    op.alter_column('edi_messages', 'data_ricezione', new_column_name='received_at', existing_type=sa.DateTime())
    op.alter_column('edi_messages', 'data_elaborazione', new_column_name='processed_at', existing_type=sa.DateTime())
    op.alter_column('edi_messages', 'errore', new_column_name='error_message', existing_type=sa.Text())
    op.alter_column('edi_messages', 'tentativi', new_column_name='retry_attempts', existing_type=sa.Integer())
    op.alter_column('edi_messages', 'riferimento_interno', new_column_name='internal_reference', existing_type=sa.String(100))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('integrations', 'name', new_column_name='nome', existing_type=sa.String(100), nullable=False)
    op.alter_column('integrations', 'connection_type', new_column_name='tipoConnessione', existing_type=sa.String(50))
    op.alter_column('integrations', 'configuration', new_column_name='configurazione', existing_type=sa.JSON())
    op.alter_column('integrations', 'last_sync', new_column_name='ultimaSincronizzazione', existing_type=sa.DateTime())
    op.alter_column('integrations', 'next_sync', new_column_name='prossimaSincronizzazione', existing_type=sa.DateTime())
    op.alter_column('integrations', 'messages_in_queue', new_column_name='messaggiInCoda', existing_type=sa.Integer())
    op.alter_column('integrations', 'messages_processed', new_column_name='messaggiProcessati', existing_type=sa.Integer())
    op.alter_column('integrations', 'last_error', new_column_name='ultimoErrore', existing_type=sa.Text())
    op.alter_column('integrations', 'is_enabled', new_column_name='abilitato', existing_type=sa.Boolean())
    op.alter_column('integrations', 'schedule_config', new_column_name='scheduleConfig', existing_type=sa.JSON())

    op.alter_column('integration_logs', 'action', new_column_name='azione', existing_type=sa.String(100))
    op.alter_column('integration_logs', 'message', new_column_name='messaggio', existing_type=sa.Text())
    op.alter_column('integration_logs', 'details', new_column_name='dettagli', existing_type=sa.JSON())
    op.alter_column('integration_logs', 'duration_ms', new_column_name='durata_ms', existing_type=sa.Integer())
    op.alter_column('integration_logs', 'records_processed', new_column_name='record_processati', existing_type=sa.Integer())
    op.alter_column('integration_logs', 'records_with_errors', new_column_name='record_errori', existing_type=sa.Integer())
    op.alter_column('integration_logs', 'is_successful', new_column_name='successo', existing_type=sa.Boolean())
    op.alter_column('integration_logs', 'error_message', new_column_name='errore', existing_type=sa.Text())

    op.alter_column('integration_credentials', 'name', new_column_name='nome', existing_type=sa.String(100), nullable=False)
    op.alter_column('integration_credentials', 'encrypted_value', new_column_name='valore_criptato', existing_type=sa.Text(), nullable=False)
    op.alter_column('integration_credentials', 'valid_from', new_column_name='valido_dal', existing_type=sa.DateTime())
    op.alter_column('integration_credentials', 'valid_until', new_column_name='valido_fino', existing_type=sa.DateTime())
    op.alter_column('integration_credentials', 'credential_metadata', new_column_name='model_metadata', existing_type=sa.JSON())

    op.alter_column('integration_mappings', 'entity', new_column_name='entita', existing_type=sa.String(50))
    op.alter_column('integration_mappings', 'source_fields', new_column_name='campi_origine', existing_type=sa.JSON(), nullable=False)
    op.alter_column('integration_mappings', 'destination_fields', new_column_name='campi_destinazione', existing_type=sa.JSON(), nullable=False)
    op.alter_column('integration_mappings', 'transformations', new_column_name='trasformazioni', existing_type=sa.JSON())
    op.alter_column('integration_mappings', 'validations', new_column_name='validazioni', existing_type=sa.JSON())
    op.alter_column('integration_mappings', 'is_active', new_column_name='attivo', existing_type=sa.Boolean())

    op.alter_column('edi_messages', 'message_type', new_column_name='tipo_messaggio', existing_type=sa.String(50))
    op.alter_column('edi_messages', 'message_number', new_column_name='numero_messaggio', existing_type=sa.String(100))
    op.alter_column('edi_messages', 'direction', new_column_name='direzione', existing_type=sa.String(10))
    op.alter_column('edi_messages', 'format', new_column_name='formato', existing_type=sa.String(20))
    op.alter_column('edi_messages', 'sent_at', new_column_name='data_invio', existing_type=sa.DateTime())
    op.alter_column('edi_messages', 'received_at', new_column_name='data_ricezione', existing_type=sa.DateTime())
    op.alter_column('edi_messages', 'processed_at', new_column_name='data_elaborazione', existing_type=sa.DateTime())
    op.alter_column('edi_messages', 'error_message', new_column_name='errore', existing_type=sa.Text())
    op.alter_column('edi_messages', 'retry_attempts', new_column_name='tentativi', existing_type=sa.Integer())
    op.alter_column('edi_messages', 'internal_reference', new_column_name='riferimento_interno', existing_type=sa.String(100))
    # ### end Alembic commands ###
